class Ciudades {
  static final List<String> citys = [
    "Altamira",
    "Arenoso",
    "Azua",
    "Bajos de Haina",
    "Baní",
    "Bánica",
    "Barahona",
    "Bayaguana",
    "Bisonó",
    "Boca Chica",
    "Bohechío",
    "Bonao",
    "Cabral",
    "Cabrera",
    "Cambita Garabitos",
    "Castañuelas",
    "Castillo",
    "Cayetano Germosén",
    "Cevicos",
    "Comendador",
    "Constanza",
    "Consuelo",
    "Cotuí",
    "Cristóbal",
    "Dajabón",
    "Duvergé",
    "El Cercado",
    "El Factor",
    "El Llano",
    "El Peñón",
    "El Pino",
    "El Seibo",
    "El Valle",
    "Enriquillo",
    "Esperanza",
    "Estebanía",
    "Eugenio María de Hostos",
    "Fantino",
    "Fundación",
    "Galván",
    "Gaspar Hernández",
    "Guananico",
    "Guayabal",
    "Guayacanes",
    "Guaymate",
    "Guayubín",
    "Hato Mayor",
    "Higüey",
    "Hondo Valle",
    "Imbert",
    "Jamao Al Norte",
    "Jánico",
    "Jaquimeyes",
    "Jarabacoa",
    "Jima Abajo",
    "Jimaní",
    "Juan de Herrera",
    "Juan Santiago",
    "La Ciénaga",
    "La Descubierta",
    "Laguna Salada",
    "La Mata",
    "La Romana",
    "Las Charcas",
    "Las Guáranas",
    "Las Matas de Farfán",
    "Las Matas de Santa Cruz",
    "Las Salinas",
    "Las Terrenas",
    "Las Yayas de Viajama",
    "La Vega",
    "Licey al Medio",
    "Loma de Cabrera",
    "Los Alcarrizos",
    "Los Cacaos",
    "Los Hidalgos",
    "Los Llanos",
    "Los Ríos",
    "Luperón",
    "Maimón",
    "Mao",
    "Matanzas",
    "Mella",
    "Miches",
    "Moca",
    "Monción",
    "Monte Cristi",
    "Monte Plata",
    "Nagua",
    "Neiba",
    "Nizao",
    "Oviedo",
    "Padre Las Casas",
    "Paraíso",
    "Partido",
    "Pedernales",
    "Pedro Brand",
    "Pedro Santana",
    "Pepillo Salcedo",
    "Peralta",
    "Peralvillo",
    "Piedra Blanca",
    "Pimentel",
    "Polo",
    "Postrer Río",
    "Pueblo Viejo",
    "Puerto Plata",
    "Puñal",
    "Quisqueya",
    "Ramón Santana",
    "Rancho Arriba",
    "Restauración",
    "Río San Juan",
    "Sabana de la Mar",
    "Sabana Grande de Boyá",
    "Sabana Grande de Palenque",
    "Sabana Iglesia",
    "Sabana Larga",
    "Sabana Yegua",
    "Salcedo",
    "Samaná",
    "San Antonio de Guerra",
    "Sánchez",
    "San Cristóbal",
    "San Francisco de Macorís",
    "San Gregorio de Nigua",
    "San Ignacio de Sabaneta",
    "San José de Las Matas",
    "San José de Ocoa",
    "San Juan",
    "San Pedro de Macorís",
    "San Rafael del Yuma",
    "Santiago de los Caballeros",
    "Santo Domingo Este",
    "Santo Domingo Norte",
    "Santo Domingo Oeste",
    "Sosúa",
    "Tábara Arriba",
    "Tamayo",
    "Tamboril",
    "Tenares",
    "Vallejuelo",
    "Vicente Noble",
    "Villa Altagracia",
    "Villa González",
    "Villa Hermosa",
    "Villa Isabela",
    "Villa Jaragua",
    "Villa Los Almácigos",
    "Villa Montellano",
    "Villa Riva",
    "Villa Tapia",
    "Villa Vásquez",
    "Yaguate",
    "Yamasá",
  ];
}
